// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jexicpmnkulknlppyiuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleGljcG1ua3Vsa25scHB5aXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDg0MTksImV4cCI6MjA1NTc4NDQxOX0.vGJmJuuexs2vLoc-ASif87w7aDhrwBGUMQTcAu6zbvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);